#!/bin/sh
 
#
# chkconfig: 35 99 99
# description: wmw msg-server base on node.js
#
 
. /etc/rc.d/init.d/functions
 
USER="root"
NAME=wmw-msg-server
NODE_ENV=production
DAEMON="/usr/local/bin/node"
ROOT_DIR="/opt/wmw/Daemon/nodejs"
 
SERVER="$ROOT_DIR/cluster.js"
LOG_FILE="/var/log/$NAME.log"
PID_FILE="/var/run/nodejs/$NAME.pid"
LOCK_FILE="/var/lock/subsys/$NAME"
 
do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                runuser -l "$USER" -c "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}
 
case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
		status)
		        status -p $PID_FILE $DAEMON
				RETVAL=$?
				;;                
        *)
                echo "Usage: $0 {start|stop|restart|status}"
                RETVAL=1
esac
 
exit $RETVAL